DEFAULT_DELIMITER = ' '
COMMENT_SYMBOL = '#'
NO_POP_FUNCTIONS = ['print']
PLACEHOLDER_FUNCTIONS = ['read']
PLACEHOLDER_SYMBOL = '$'
IF_BLOCK_SYMBOLS = ('{', '}')
IF_BLOCK_PLACEHOLDER = '@'
LOOP_BLOCK_SYMBOLS = ('(', ')')
LOOP_BLOCK_PLACEHOLDER = '&'

DEBUG = True
